all:
	gcc -o 03_array_indexing 03_array_indexing.c
	gcc -o 04_out_of_bounds_memory 04_out_of_bounds_memory.c -fno-stack-protector
	gcc -o 05_out_of_bounds_fptr 05_out_of_bounds_fptr.c -fno-stack-protector -no-pie
	gcc -o 06_out_of_bounds_ret 06_out_of_bounds_ret.c -fno-stack-protector -no-pie
	gcc -o 07_uninitialized_mem 07_uninitialized_mem.c -fno-stack-protector
	gcc -o 08_fmt_demo 08_fmt_demo.c -m32
